SELECT 
 Id
,CCS_Country_Code__c
,CCS_Date_of_Birth__c
,CCS_Email__c
,CCS_Facility_ID__c
,CCS_First_Name__c
,CCS_Is_Card_Needed__c
,CCS_Last_Name__c
,CCS_Level_of_Control__c
,CCS_Limit__c
,CCS_Mobile_Number__c
,CCS_Number_of_Cards__c
,CCS_Title__c
,ConnectionReceivedId
,ConnectionSentId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,IsDeleted
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,Name
,SystemModstamp
FROM rskcsp_ds_cardholder ;

SELECT 
 Id
,CCS_Country_Code__c
,CCS_Date_of_Birth__c
,CCS_Email__c
,CCS_Facility_ID__c
,CCS_First_Name__c
,CCS_Is_Card_Needed__c
,CCS_Last_Name__c
,CCS_Level_of_Control__c
,CCS_Limit__c
,CCS_Mobile_Number__c
,CCS_Number_of_Cards__c
,CCS_Title__c
,ConnectionReceivedId
,ConnectionSentId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,IsDeleted
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,Name
,SystemModstamp
FROM 

rskcsp_ds_cardholder_staging;


SELECT 
 Id
,CCS_Country_Code__c
,CCS_Date_of_Birth__c
,CCS_Email__c
,CCS_Facility_ID__c
,CCS_First_Name__c
,CCS_Is_Card_Needed__c
,CCS_Last_Name__c
,CCS_Level_of_Control__c
,CCS_Limit__c
,CCS_Mobile_Number__c
,CCS_Number_of_Cards__c
,CCS_Title__c
,ConnectionReceivedId
,ConnectionSentId
,CreatedById
,CreatedDate
,CurrencyIsoCode
,IsDeleted
,LastActivityDate
,LastModifiedById
,LastModifiedDate
,LastReferencedDate
,LastViewedDate
,Name
,SystemModstamp
FROM rskcsp_ds_cardholder_curated;
